config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resource :personnages do
    resources :objets
end
  root to: "personnages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/objets_controller.rb
class ObjetsController < ApplicationController
    def new
        @personnage = params.to_enum.to_h
    end

    def create
        @item = params[:item].to_enum.to_h
        @id = params[:id]
        url = URI("https://jeu-api.herokuapp.com/api/v1/personnages/"+@id+"/objets")
        http = Net::HTTP.new(url.host, url.port)
        req = Net::HTTP::Post.new(url.path, 'Content-Type' => 'application/json')
        req.body = @item.to_json
        http.use_ssl = (url.scheme == "https")
        res = http.request(req)
        logger.debug @item
        logger.debug @id
        redirect_to personnages_path("id"=>@id)
    end

    def edit
        @item = params[:item].to_enum.to_h
        @persoID = params[:persoID]
    end

    def update
        @item = params[:item].to_enum.to_h
        @idPerso = params[:idPerso]
        @idItem = params[:id]
        logger.debug @item
        logger.debug @idPerso
        url = URI("https://jeu-api.herokuapp.com/api/v1/personnages/"+@idPerso+"/objets/"+@idItem)
        http = Net::HTTP.new(url.host, url.port)
        req = Net::HTTP::Patch.new(url.path, 'Content-Type' => 'application/json')
        req.body = @item.to_json
        http.use_ssl = (url.scheme == "https")
        res = http.request(req)
        redirect_to personnages_path("id"=>@idPerso)
    end

    def destroy
        url = URI("https://jeu-api.herokuapp.com/api/v1/personnages/"+params['persoID']+"/objets/"+params['id'])
        http = Net::HTTP.new(url.host, url.port)
        req = Net::HTTP::Delete.new(url.path)
        http.use_ssl = (url.scheme == "https")
        res = http.request(req)
        redirect_to personnages_path("id"=>params['persoID'])
    end
end

app/controllers/personnages_controller.rb
class PersonnagesController < ApplicationController
    require 'json'
    require 'open-uri'
    require 'net/http'
    require 'uri'
    def index
        if params[:query].present?
			url = "https://jeu-api.herokuapp.com/api/v1/personnages?query="+ params[:query]
		  else
			url = "https://jeu-api.herokuapp.com/api/v1/personnages"
		end
        github_answer = open(url).read
        @hash_github = JSON.parse(github_answer)
    end

    def create
        @personnage = params[:pseudo].to_enum.to_h
        url = URI("https://jeu-api.herokuapp.com/api/v1/personnages")
        http = Net::HTTP.new(url.host, url.port)
        req = Net::HTTP::Post.new(url.path, 'Content-Type' => 'application/json')
        http.use_ssl = (url.scheme == "https")
        req.body = @personnage.to_json
        res = http.request(req)
        redirect_to root_path
    end

    def new
        
    end

    def show
        url = "https://jeu-api.herokuapp.com/api/v1/personnages/" + params['id']
        github_answer = open(url).read
        @hash_github = JSON.parse(github_answer)
    end

    def edit
        url = "https://jeu-api.herokuapp.com/api/v1/personnages/" + params['id']
        github_answer = open(url).read
        @personnage = JSON.parse(github_answer).to_enum.to_h
    end

    def update
        @personnage = params[:pseudo].to_enum.to_h
        url = URI("https://jeu-api.herokuapp.com/api/v1/personnages/"+ params[:pseudo][:id])
        http = Net::HTTP.new(url.host, url.port)
        req = Net::HTTP::Patch.new(url.path, 'Content-Type' => 'application/json')
        req.body = @personnage.to_json
        http.use_ssl = (url.scheme == "https")
        res = http.request(req)
        logger.debug @personnage
        redirect_to personnages_path(@personnage)
    end

    def destroy
        url = URI("https://jeu-api.herokuapp.com")
        http = Net::HTTP.new(url.host, url.port).delete("/api/v1/personnages/" + params['id'])
        redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/objets_helper.rb
module ObjetsHelper
end

app/helpers/personnages_helper.rb
module PersonnagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JeuApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/objets/edit.html.erb
<%= form_with method: :patch,  url: personnages_objet_path(@item["id"],"idPerso", "item") do %>
  <%= label_tag("item[name]", "Nom :") %>
  <%= text_field_tag("item[name]", @item["name"]) %>
  <%= label_tag("item[stat1]", "Statistique principale :") %>
  <%= number_field_tag("item[stat1]", @item["stat1"]) %>
  <%= label_tag("item[stat2]", "Statistique secondaire :") %>
  <%= number_field_tag("item[stat2]", @item["stat2"]) %>
  <%= label_tag("item[rarety]", "Rareté :") %>
  <%= text_field_tag("item[rarety]", @item["rarety"]) %>
  <%= hidden_field_tag("idPerso" , @persoID) %>
  <%= submit_tag("Update") %>
<% end %>

app/views/objets/new.html.erb
<%= form_with method: :post,  url: personnages_objets_path("item","id") do %>
  <%= label_tag("item[name]", "Nom :") %>
  <%= text_field_tag("item[name]") %>
  <%= label_tag("item[stat1]", "Statistique principale :") %>
  <%= number_field_tag("item[stat1]") %>
  <%= label_tag("item[stat2]", "Statistique secondaire :") %>
  <%= number_field_tag("item[stat2]") %>
  <%= label_tag("item[rarety]", "Rareté :") %>
  <%= text_field_tag("item[rarety]") %>
  <%= hidden_field_tag("id" , @personnage["id"]) %>
  <%= submit_tag("Create") %>
<% end %>

app/views/personnages/edit.html.erb
<%= form_with method: :patch,  url: personnages_path(@personnage["id"],"pseudo") do %>
  <%= label_tag("pseudo[name]", "Nom:") %>
  <%= text_field_tag("pseudo[name]", @personnage["name"]) %>
  <%= label_tag("pseudo[niveau]", "Niveau:") %>
  <%= number_field_tag("pseudo[niveau]", @personnage["niveau"]) %>
  <%= label_tag("pseudo[personnage_class]", "Classe:") %>
  <%= text_field_tag("pseudo[personnage_class]", @personnage["personnage_class"]) %>
  <%= hidden_field_tag("pseudo[id]" , @personnage["id"]) %>
  <%= submit_tag("Update") %>
<% end %>

app/views/personnages/index.html.erb
<h1> LE MMORPG DE L'ANNEE : </h1>

<h2> Les personnages du serveur : </h2>

 <%= form_tag root_path, :method => 'get'  do %>
   <%= text_field_tag :query, params[:query]%>
   <%= submit_tag "Search", :name => nil  %>
 <% end %>

<table>
  <tr>
    <th>Nom du personnage : </th>
    <th>Classe : </th>
    <th>Niveau : </th>
    <th>Date de création : </th>
    <th></th>
  </tr>
 
  <% @hash_github.each do |personnage| %>
    <tr>
      <td><%= personnage['name'] %></td>
      <td><%= personnage['personnage_class'] %></td>
      <td><%= personnage['niveau'] %></td>
      <td><%= personnage['created_at'] %></td>
      <td><%= link_to 'Show', personnages_path(personnage) %></td>
      <td><%= link_to 'Update', edit_personnages_path(personnage) %></td>
      <td><%= link_to "Delete", personnages_path(personnage), method: :delete, data: { confirm: "Are you sure ?"} %></td>
    </tr>
  <% end %>

  <p><%= link_to 'Create new', new_personnages_path %><p>
</table>

app/views/personnages/new.html.erb
<%= form_with method: :post,  url: personnages_path("pseudo") do %>
  <%= label_tag("pseudo[name]", "Nom:") %>
  <%= text_field_tag("pseudo[name]") %>
  <%= label_tag("pseudo[niveau]", "Niveau:") %>
  <%= number_field_tag("pseudo[niveau]") %>
  <%= label_tag("pseudo[personnage_class]", "Classe:") %>
  <%= text_field_tag("pseudo[personnage_class]") %>
  <%= submit_tag("Create") %>
<% end %>

app/views/personnages/show.html.erb
<h2>Personnage : <%= @hash_github['name'] %></h2>
<p> Classe : <%= @hash_github['personnage_class'] %></p>
<p> Niveau : <%= @hash_github['niveau'] %></p>

<p> Inventaire : </p>
<p><%= link_to 'Create new objet', new_personnages_objet_path(@hash_github) %><p>
<table>
    <tr>
        <th>Nom</th>
        <th>Statistique Principale</th>
        <th>Statistique Secondaire</th>
        <th>Rareté</th>
        <th></th>
    </tr>
    <% @hash_github['objets'].each do |item| %>
        <tr>
        <td><%= item['name'] %></td>
        <td><%= item['stat1'] %></td>
        <td><%= item['stat2'] %></td>
        <td><%= item['rarety'] %></td>
        <td><%= link_to 'Update', edit_personnages_objet_path(item['id'], "persoID"=>@hash_github['id'], "item" => item) %></td>
        <td><%= link_to "Delete", personnages_objet_path(item['id'], "persoID"=>@hash_github['id']), method: :delete, data: { confirm: "Are you sure ?"} %></td>
        </tr>
    <% end %>
</table>

<p><%= link_to 'Go back to the list', root_path %><p>